data:extend({

	{
		type = "bool-setting",
		name = "armor-progression-inventory-size-enable",
		setting_type = "startup",
		default_value = true,
		order = "a",
	},
	{	
		type = "int-setting",
		name = "armor-progression-inventory-size",
		setting_type = "startup",
		default_value = 5,
		minimum_value = 3,
		maximum_value = 25,
		order = "aa",
	},
	{
		type = "bool-setting",
		name = "armor-progression-debug",
		setting_type = "runtime-global",
		default_value = false,
		order = "ab",
	},
	{
		type = "bool-setting",
		name = "armor-progression-speed-enable",
		setting_type = "startup",
		default_value = true,
		order = "ac",
	},
	{
		type = "double-setting",
		name = "armor-progression-speed-mod-none",
		setting_type = "runtime-global",
		default_value = 1,
		minimum_value = 0.1,
		maximum_value = 1,
		order = "aca",
	},
	{	
		type = "double-setting",
		name = "armor-progression-speed-mod-light",
		setting_type = "runtime-global",
		default_value = 0.8,
		minimum_value = 0.1,
		maximum_value = 1,
		order = "b",
	},
	{	
		type = "double-setting",
		name = "armor-progression-speed-mod-heavy",
		setting_type = "runtime-global",
		default_value = 0.7,
		minimum_value = 0.1,
		maximum_value = 1,
		order = "c",
	},
	{	
		type = "double-setting",
		name = "armor-progression-speed-mod-modular",
		setting_type = "runtime-global",
		default_value = 0.6,
		minimum_value = 0.1,
		maximum_value = 1,
		order = "d",
	},
	{	
		type = "double-setting",
		name = "armor-progression-speed-mod-power",
		setting_type = "runtime-global",
		default_value = 0.5,
		minimum_value = 0.1,
		maximum_value = 1,
		order = "e",
	},
	{	
		type = "double-setting",
		name = "armor-progression-speed-mod-power-mk2",
		setting_type = "runtime-global",
		default_value = 0.5,
		minimum_value = 0.1,
		maximum_value = 1,
		order = "f",
	},
	{
		type = "bool-setting",
		name = "armor-progression-mining-speed-enable",
		setting_type = "startup",
		default_value = true,
		order = "fa",
	},
	{
		type = "double-setting",
		name = "armor-progression-mining-speed-mod-normal",
		setting_type = "runtime-global",
		default_value = 0.1,
		minimum_value = 0.01,
		maximum_value = 1,
		order = "g",
	},
	{	
		type = "double-setting",
		name = "armor-progression-mining-speed-mod-steelaxe",
		setting_type = "runtime-global",
		default_value = 0.5,
		minimum_value = 0.01,
		maximum_value = 1,
		order = "h",
	},
	{
		type = "bool-setting",
		name = "armor-progression-crafting-speed-enable",
		setting_type = "startup",
		default_value = true,
		order = "ha",
	},
	{
		type = "double-setting",
		name = "armor-progression-crafting-speed-mod-normal",
		setting_type = "runtime-global",
		default_value = 0.016,
		minimum_value = 0.01,
		maximum_value = 1,
		order = "i",
	},
	{	
		type = "double-setting",
		name = "armor-progression-crafting-speed-mod-steelaxe",
		setting_type = "runtime-global",
		default_value = 0.033,
		minimum_value = 0.01,
		maximum_value = 1,
		order = "j",
	},
	{	
		type = "int-setting",
		name = "armor-progression-inventory-mod-light",
		setting_type = "runtime-global",
		default_value = 15,
		minimum_value = 10,
		maximum_value = 100,
		order = "ka",
	},
	{	
		type = "int-setting",
		name = "armor-progression-inventory-mod-heavy",
		setting_type = "runtime-global",
		default_value = 35,
		minimum_value = 10,
		maximum_value = 100,
		order = "kb",
	},
	{	
		type = "int-setting",
		name = "armor-progression-inventory-mod-modular",
		setting_type = "runtime-global",
		default_value = 55,
		minimum_value = 10,
		maximum_value = 100,
		order = "kc",
	},
	{	
		type = "int-setting",
		name = "armor-progression-inventory-mod-power",
		setting_type = "runtime-global",
		default_value = 75,
		minimum_value = 10,
		maximum_value = 100,
		order = "kd",
	},
	{	
		type = "int-setting",
		name = "armor-progression-inventory-mod-power-mk2",
		setting_type = "runtime-global",
		default_value = 75,
		minimum_value = 10,
		maximum_value = 100,
		order = "ke",
	},
	{
		type = "bool-setting",
		name = "armor-progression-reach-enable",
		setting_type = "startup",
		default_value = true,
		order = "la",
	},
	{	
		type = "int-setting",
		name = "armor-progression-reach",
		setting_type = "startup",
		default_value = 1,
		minimum_value = 1,
		maximum_value = 100,
		order = "lb",
	},
	{	
		type = "int-setting",
		name = "armor-progression-reach-mod-light",
		setting_type = "runtime-global",
		default_value = 3,
		minimum_value = 1,
		maximum_value = 100,
		order = "ma",
	},
	{	
		type = "int-setting",
		name = "armor-progression-reach-mod-heavy",
		setting_type = "runtime-global",
		default_value = 5,
		minimum_value = 1,
		maximum_value = 100,
		order = "mb",
	},
	{	
		type = "int-setting",
		name = "armor-progression-reach-mod-modular",
		setting_type = "runtime-global",
		default_value = 7,
		minimum_value = 1,
		maximum_value = 100,
		order = "mc",
	},
	{	
		type = "int-setting",
		name = "armor-progression-reach-mod-power",
		setting_type = "runtime-global",
		default_value = 9,
		minimum_value = 1,
		maximum_value = 100,
		order = "md",
	},
	{	
		type = "int-setting",
		name = "armor-progression-reach-mod-power-mk2",
		setting_type = "runtime-global",
		default_value = 9,
		minimum_value = 1,
		maximum_value = 100,
		order = "me",
	},
})